# Generated by Django 4.2.5 on 2024-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
